#mysql
#spring:
#  datasource:
#    url: jdbc:mysql://localhost:3306/testone?useUnicode=true&characterEncoding=utf8&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=GMT%2B8
#    username: root
#    password: 123456
#    driver-class-name: com.mysql.cj.jdbc.Driver

#oracle
#spring:
#  datasource:
#    url: jdbc:oracle:thin:@localhost:1521:XE
#    username: system
#    password: 123456
#    driver-class-name: oracle.jdbc.OracleDriver



#activemq:
#  port: 9090
#  broker-url: tcp://127.0.0.1:61616
#  in-memory: true
#  non-blocking-redelivery: false
#  send-timeout: 0
#  user: admin
#  password: admin
#  pool:
#    # 使用flase,此处改为true报错，不清楚什么原因
#    enabled: false
#    max-connections: 10
#queueName: publish.queue
#topicName: publish.topic

#topic
#jms:
#  pub-sub-domain: true
server:
  port: 6060
spring:
  elasticsearch:
    rest:
      username: elastic
      password: 123456

  datasource:
#    url: jdbc:mysql://localhost:3306/testone?useUnicode=true&characterEncoding=utf8&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=GMT%2B8
#    username: root
#    password: 123456
#    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:sqlserver://localhost:1433;DatabaseName=testone
    username: sa
    password: 123456
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
  messages:
    basename: i18n/Messages,i18n/Pages
    jms:
      pub-sub-domain: true  # 配置消息的类型，如果是true则表示为topic消息，如果为false表示Queue消息
    activemq:
      user: admin    # 连接用户名

      password: admin   # 连接密码
      broker-url: tcp://localhost:61616 # 消息组件的连接主机信息
      send-timeout: 0

mybatis:
  mapper-locations: classpath:mapper/*.xml  #注意：一定要对应mapper映射xml文件的所在路径

log:
  path: H:/logs/mytest
